### ISSUE TITLE
`test_pytket_with_wasm` fails when run after `test_pytket_to_phir_no_machine_at_all`

### ISSUE THREAD

**Issue by Asa-Kosto-QTM** [CQCL/pytket-phir#108]
These 2 tests are probably interacting somehow. When `test_pytket_with_wasm` runs first, it passes, but when `test_pytket_phir_no_machine_at_all` runs first, `test_pytket_with_wasm` fails. It is weird that moving these tests around within the file changes whether they pass or not, they should be totally independent.

This also occurs on the 3q-rz-bug branch when run after `test_three_qubit_rz_exec_order_preserved`.

**Comment by qartik** [comment]
A hach fix is merged in https://github.com/CQCL/pytket-phir/commit/7546a8747cfd7e53e6d0711cd098083d1a49e639
