### ISSUE TITLE
`UINTMAX` is hard-coded as `2^32 - 1`

### ISSUE THREAD

**Issue by qartik** [CQCL/pytket-phir#165]
> `UINTMAX` is hard-coded as $2^{32} - 1$, but if we have non-32-bit registers we'd want a different value. In pytket's QASM converters there is a `maxwidth` parameter that can be used to set this value (defaulting to 32). Could something similar be done here?

_Originally posted by @cqc-alec in https://github.com/CQCL/pytket-phir/pull/162#discussion_r1559027873_

**Comment by qartik** [comment]
Hi @cqc-alec, is it possible to obtain the `maxwidth` parameter from a `Circuit`, let's say if the program's source is not QASM?

I don't currently see a way to remove this hard coded value without being able to uniformly access it for all programs.

In any case, for QASM programs the value is correct.

**Comment by cqc-alec** [comment]
> Hi @cqc-alec, is it possible to obtain the `maxwidth` parameter from a `Circuit`, let's say if the program's source is not QASM?
> 
> I don't currently see a way to remove this hard coded value without being able to uniformly access it for all programs.
> 
> In any case, for QASM programs the value is correct.

No it's not possible to obtain from a pytket `Circuit`, because it's a lower-level property -- a `Circuit` can have arbitrarily-sized classical "registers" (in scare quotes because it doesn't really have registers at all, just bits with labels). So this parameter depends on knowledge of the backend.

**Comment by qartik** [comment]
In that case, I will let the value as is. We can come back to it when the backend changes.

**Comment by qartik** [comment]
Reopening to make maxwidth a parameter to pytket-phir as discussed.
