### ISSUE TITLE
Add support for `ClExprOp` in pytket-to-PHIR conversion

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-phir#250]

**Comment by qartik** [comment]
Hi @cqc-alec could you describe what `ClExprOp` is? I tried looking at the pytket-qir issue/PR as well, but it wasn't immediately clear.

**Comment by cqc-alec** [comment]
It is a replacement for `ClassicalExpBox`, designed to avoid some of the issues that arise with the latter's implementation using `logic_exp` in TKET. QASM conversion by default still produces `ClassicalExpBox` (as before), but has an optional argument `use_clexpr` that produces the new type instead. Eventually this will become the default and `ClassicalExpBox` will be deprecated (but first we need to make sure all the converters can handle it).
