### ISSUE TITLE
Handle common quantum program inputs

### ISSUE THREAD

**Issue by qciaran** [CQCL/pytket-phir#49]
Provide functions to accept extend OpenQASM 2.0 string and pytket circuit Python. Look into accepting qiskit python programs.

qasm -> pytket function seems to require a file. If possible, avoid generating a temporary file and take direct QASM string input.

**Comment by neal-erickson** [comment]
@qciaran I split the Qiskit enhancement into its own issue, since that will be a bit more effort.

**Comment by qartik** [comment]
QASM handled by #69, Qiskit support being tracked in #68, closing.
