### ISSUE TITLE
Add Wasm support

### ISSUE THREAD

**Issue by qciaran** [CQCL/pytket-phir#50]
Related to issue #49. Add support for programs with Wasm to generate appropriate PHIR. 

PECOS (https://github.com/PECOS-packages/PECOS/blob/b71596a3520b0f48f844aabf5cf29a77c3a79ecd/tests/integration/test_phir.py#L36) has a test showing that direct input of PHIR + Wasm will run.

**Comment by cqc-alec** [comment]
This issue here is just WASM support, right? I don't think pytket-phir needs to know anything about QASM?

**Comment by qciaran** [comment]
I just mean taking in the combination of qasm with Wasm. Although I guess technically its input is pytket circuits. I'll drop the mention of qasm.
